"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Javier Alvarez"
email = "javier.alvarez@allthingsembedded.net"

[ui]
default-command = "log"

# See https://github.com/jj-vcs/jj/discussions/4690
[[--scope]]
--when.commands = ["diff", "show"]

[--scope.ui]
# https://github.com/jj-vcs/jj/blob/v0.25.0/docs/config.md#processing-contents-to-be-paged
pager = "delta"
# NOTE: this is required when using `delta` as a pager
diff.format = "git"
